/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/components/AboutView.vue')['default']
    CartView: typeof import('./src/components/CartView.vue')['default']
    ContentView: typeof import('./src/components/ContentView.vue')['default']
    FavouriteView: typeof import('./src/components/FavouriteView.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LogIn: typeof import('./src/components/LogIn.vue')['default']
    ProfileView: typeof import('./src/components/ProfileView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
  }
}
